### ISSUE TITLE
context.drizzle.contracts async issue

### ISSUE THREAD

**Issue by JFGHT** [trufflesuite/drizzle-react-components#34]
Basically, this line 
`
// Get the contract ABI
const abi = this.contracts[this.props.contract].abi;
` fails because `this.contracts` is empty at refreshing the page, the info comes later.

**Comment by Garoth** [comment]
+1 to this issue. Btw that `abi` line in ContractData isn't even used...

But the real issue seems to be that drizzle devs assume drizzle is sync'd and ready to go at constructor time, which is done consistently in all the examples. I'm currently working around this issue by doing all the contract cacheCalls in `render`, and checking if the results are in. Part of the problem is also that drizzle-react uses some deprecated APIs, making it only somewhat compatible with React 16.

**Comment by honestbonsai** [comment]
This line has since been removed, please reopen the issue if the problem persists. Thanks!
